### PR TITLE
Add time_offset support

### PR DESCRIPTION
**Pull request by mjseppa**
Add time_offset capability to the interface for finetuning timestamps.

Quick implementation only tested on BPearl.

### CODE REVIEW

**Comment by ronzheng1006** [comment]
Hi mjseppa,

Thanks for your PR. 

Yes, the timestamp is not accurate when driver_param.use_liar_clock is false, so time_offset is meaningful.

However time_offset is not enough, because Linux thread switch sometimes affects the timestamp so much.

It is suggest to set use_lidar_clock to be true, so the lidar will generate the timestamp. It should be accurate.

**Comment by mjseppa** [comment]
We got bunch of 16-lines with the default FW and need to apply 1s + PPS width (1.1s for 100ms pulse) for the clock to be correct even with the use_lidar_clock: true with GPS+PPS input.

**Comment by ronzheng1006** [comment]
Hi mjseppa, 

Thanks for your feedback.  We are asking the partner to have a look at this.

**Comment by RS-Alex** [comment]
Hi mjseppa
May I know your current status of the timestamp?  Is it too slow or too fast? If so how much is the gap?

**Comment by RS-Alex** [comment]
> Add time_offset capability to the interface for finetuning timestamps.
> 
> Quick implementation only tested on BPearl.

Can you please send a pcap file to alex.guo@robosense.cn? We will check the pointcloud.

**Comment by mjseppa** [comment]
Hi Alex,

This was alredy identified as FW issue with Jimmy and Armin in March 2021.
Email chain is "BPearl GPS synchronization", same was on RS-16. I assume this is fixed on newer ones as we got fixed FW for some of the units, but we found it easier to fix the driver as the offset was known (1s+pps width).
I have not tested newer shipped units if they have the updated FW. But atleast with rising PPS to indicate the sync all older ones had 1s+pps width. The time offset fix has worked fine now for almost a year on multi RS-16 robots.

**Comment by RS-Alex** [comment]
Hi @mjseppa 
Thanks for the information. I checked the Email chain and the issue last year was indeed confirmed as FW issue. The new released version has already fixed the issue and you will no longer have the offset problem.
For the old units you can upgrade the bottom firmware or simply fix the timestamp in the driver, as the offset is fixed.

**Comment by mjseppa** [comment]
Ok. Without HW sync we've found that adding time_offset: 0.05 also makes the output match IMU movements better.

**Pull request closed without merging**
