### PR TITLE
ROS1 and ROS2 Config param

### PR DESCRIPTION
**Pull request by Timple**
Add ROS2 parameter on top of #39 

Thanks @mtlazaro for the initial part!

### CODE REVIEW

**Comment by Timple** [comment]
Can I get any comment on this PR?

**Comment by ronzheng1006** [comment]
We have merged your PR to the dev branch. Thank you.

**Comment by Timple** [comment]
Great!

As nobody seems to be watching the `rslidar_msg` repository. A subtle ping here for a PR there: https://github.com/RoboSense-LiDAR/rslidar_msg/pull/1

**Comment by Timple** [comment]
Merged in dev

**Comment by Timple** [comment]
Turns out this wasn't merged.

@ronzheng1006 could you please take another look at this?

**Pull request closed without merging**
